---
- hosts: ss-xr
  connection: local
  gather_facts: no

  vars:
    cli:
       host: "{{ ansible_host }}"
       username: "{{ ansible_user }}"
       password: "{{ ansible_ssh_pass }}"

  tasks:
  - iosxr_install_key:
      provider: "{{ cli }}"
      keyfile: "tftp://192.168.1.28/id_rsa_pub.b64"
    register: output
  - debug: var=output.stdout_lines
