---
- hosts: ss-xr
  connection: local
  gather_facts: no

  vars:
    cli:
       host: "{{ ansible_host }}"
       username: "{{ ansible_user }}"
       password: "{{ ansible_ssh_pass }}"
    config_file: "tftp:/192.168.1.28/add_replace.cfg"

  tasks:
  - name: compare config file to running config
    iosxr_diff_config:
      provider: "{{ cli }}"
      cfgname: "{{ config_file }}"
    register: output
  - debug: var=output.stdout_lines
