---
- hosts: ss-xr
  connection: local
  gather_facts: no

  vars:
    cli:
       host: "{{ ansible_host }}"
       username: "{{ ansible_user }}"
       password: "{{ ansible_ssh_pass }}"

  vars_prompt:
  - name: yesno
    prompt: "Are you sure you want to clear all configurations (yes/no)? "

  tasks:
  - name: clear all configurations
    iosxr_clear_config:
      provider: "{{ cli }}"
      confirm: "{{ yesno }}"
    register: output
  - debug: var=output.stdout_lines
