---
- hosts: ss-xr
  connection: local
  gather_facts: no

  vars:
    cli:
       host: "{{ ansible_host }}"
       username: "{{ ansible_user }}"
       password: "{{ ansible_ssh_pass }}"

  tasks:
  - name: clear log data
    iosxr_clear_log:
      provider: "{{ cli }}"
    register: output
  - debug: var=output.stdout_lines
