---
- hosts: ss-xr
  connection: local
  gather_facts: no

  vars:
    cli:
       host: "{{ ansible_host }}"
       username: "{{ ansible_user }}"
       password: "{{ ansible_ssh_pass }}"
       timeout: 180
    smu_name: "xrv9k-li-x-1.1.0.0-r64121I"

  tasks:
  - name: update SMU package
    iosxr_install_package:
      provider: "{{ cli }}"
      #pkgpath: "https://aermongk-dev"
      pkgpath: "tftp://192.168.1.28/"
      pkgname: "{{ smu_name }}"
      state: updated
    register: output
  - debug: var=output.stdout_lines
