---
- hosts: ss-xr
  connection: local
  gather_facts: no

  vars:
    cli:
       host: "{{ ansible_host }}"
       username: "{{ ansible_user }}"
       password: "{{ ansible_ssh_pass }}"
       timeout: 600

  tasks:
  - name: activate packages
    iosxr_upgrade_activate:
      provider: "{{ cli }}"
      pkgname: "xrv9k-li-x-1.1.0.0-r64121I xrv9k-ospf-2.0.0.0-r64121I"
    register: output
  - debug: var=output.stdout_lines
