---
- hosts: ss-xr
  connection: local
  gather_facts: no

  vars:
    cli:
       host: "{{ ansible_host }}"
       username: "{{ ansible_user }}"
       password: "{{ ansible_ssh_pass }}"

  tasks:
  - name: send Cisco XML file
    iosxr_xml_send:
      provider: "{{ cli }}"
      xmlfile: "{{ xml_file }}"
    register: output
  - debug: var=output.stdout_lines
