---
- hosts: ss-xr
  gather_facts: no

  vars:
    pkgname: 'xrv9k-mpls-2.0.0.1-r60204I.CSCxr33333'

  tasks:
  - name: 'remove package {{ pkgname }}'
    shell: 'source /etc/profile ; nsenter -t 1 -n -- sdr_instcmd install remove pkg {{ pkgname }} || true'
    register: str
  - debug: var=str.stdout_lines
