---
- hosts: ss-xr
  connection: local
  gather_facts: no

  vars:
    cli:
       host: "{{ ansible_host }}"
       username: "{{ ansible_user }}"
       password: "{{ ansible_ssh_pass }}"

  tasks:
  - iosxr_show_install_inactive:
      provider: "{{ cli }}"
    register: output
  - debug: var=output.stdout_lines
