---
- hosts: ss-xr
  gather_facts: no

  vars:
    cli:
       host: "{{ ansible_host }}"
       username: "{{ ansible_user }}"
       password: "{{ ansible_ssh_pass }}"

  tasks:
  - name: remove user cisco
    iosxr_install_config:
      provider: "{{ cli }}"
      cfgname: "/tftp://192.168.1.1/user_remove.cfg"
    register: output
  - debug: var=output.stdout_lines
