---
- hosts: ss-xr
  gather_facts: no

  vars:
    cli:
       host: "{{ ansible_host }}"
       username: "{{ ansible_user }}"
       password: "{{ ansible_ssh_pass }}"

  tasks:
  - name: get IOS-XR running configuration
    iosxr_get_config:
      provider: "{{ cli }}"
    register: output
  - debug: var=output.stdout_lines
