---
- hosts: ss-xr
  gather_facts: no
  become: yes

  vars:
    cli:
       host: "{{ ansible_host }}"
       username: "{{ ansible_user }}"
       password: "{{ ansible_ssh_pass }}"

  tasks:
  - name: apply configuration file on the IOS-XR node
    iosxr_install_config:
      provider: "{{ cli }}"
      cfgname: "/tftp://192.168.1.28/user_add.cfg"
      #label: "add_user"
    register: output
  - debug: var=output.stdout_lines
