---
- hosts: ss-xr
  gather_facts: no

  vars:
    cli:
       host: "{{ ansible_host }}"
       username: "{{ ansible_user }}"
       password: "{{ ansible_ssh_pass }}"

  tasks:
  - iosxr_cli:
      provider: "{{ cli }}"
      command: "{{ cmd }}"
    register: output
  - debug: var=output.stdout_lines
