---
- hosts: ss-xr
  gather_facts: no

  vars:
    cli:
       host: "{{ ansible_host }}"
       username: "{{ ansible_user }}"
       password: "{{ ansible_ssh_pass }}"

  tasks:
  - name: get system facts
    iosxr_get_facts:
      provider: "{{ cli }}"
    register: facts
  - debug: var=facts
